// ============================================================
//  TABÚ - Lista de 300 palabras en español para niños (8-12)
//  Cada palabra tiene 5 palabras TABÚ (no se pueden decir).
//  Formato: { p: "PALABRA", t: ["tabu1","tabu2","tabu3","tabu4","tabu5"] }
// ============================================================

const PALABRAS = [
  // ---------- ANIMALES (50) ----------
  { p: "PERRO", t: ["gato", "ladrar", "mascota", "hueso", "cola"] },
  { p: "GATO", t: ["perro", "maullar", "ratón", "bigotes", "garras"] },
  { p: "LEÓN", t: ["selva", "melena", "rugir", "rey", "fiera"] },
  { p: "ELEFANTE", t: ["trompa", "grande", "gris", "orejas", "colmillos"] },
  { p: "JIRAFA", t: ["cuello", "largo", "manchas", "alta", "África"] },
  { p: "MONO", t: ["plátano", "árbol", "selva", "cola", "trepar"] },
  { p: "CABALLO", t: ["montar", "galopar", "cola", "establo", "herradura"] },
  { p: "VACA", t: ["leche", "muu", "granja", "cuernos", "hierba"] },
  { p: "CERDO", t: ["barro", "rosa", "granja", "rabo", "jamón"] },
  { p: "OVEJA", t: ["lana", "balar", "rebaño", "pastor", "blanca"] },
  { p: "GALLINA", t: ["huevo", "granja", "cacarear", "pollito", "plumas"] },
  { p: "PATO", t: ["agua", "cuac", "nadar", "pico", "plumas"] },
  { p: "CONEJO", t: ["zanahoria", "orejas", "saltar", "madriguera", "rápido"] },
  { p: "RATÓN", t: ["queso", "pequeño", "cola", "gato", "agujero"] },
  { p: "OSO", t: ["miel", "grande", "cueva", "invierno", "peludo"] },
  { p: "LOBO", t: ["aullar", "bosque", "manada", "perro", "caperucita"] },
  { p: "ZORRO", t: ["astuto", "cola", "naranja", "bosque", "gallinas"] },
  { p: "TIGRE", t: ["rayas", "naranja", "selva", "felino", "rugir"] },
  { p: "CEBRA", t: ["rayas", "blanco", "negro", "caballo", "África"] },
  { p: "CANGURO", t: ["bolsa", "saltar", "Australia", "cola", "cría"] },
  { p: "PINGÜINO", t: ["frío", "hielo", "blanco", "negro", "nadar"] },
  { p: "DELFÍN", t: ["mar", "nadar", "saltar", "inteligente", "gris"] },
  { p: "BALLENA", t: ["mar", "grande", "agua", "azul", "chorro"] },
  { p: "TIBURÓN", t: ["mar", "dientes", "aleta", "peligroso", "pez"] },
  { p: "PEZ", t: ["agua", "nadar", "aletas", "pecera", "escamas"] },
  { p: "PULPO", t: ["mar", "tentáculos", "ocho", "tinta", "ventosas"] },
  { p: "CANGREJO", t: ["pinzas", "playa", "caparazón", "rojo", "lado"] },
  { p: "TORTUGA", t: ["caparazón", "lenta", "verde", "mar", "patas"] },
  { p: "SERPIENTE", t: ["arrastrar", "veneno", "lengua", "larga", "silbar"] },
  { p: "COCODRILO", t: ["dientes", "río", "verde", "mandíbula", "agua"] },
  { p: "RANA", t: ["saltar", "verde", "charco", "croar", "renacuajo"] },
  { p: "ARAÑA", t: ["telaraña", "patas", "insecto", "ocho", "picar"] },
  { p: "ABEJA", t: ["miel", "picar", "volar", "flor", "zumbido"] },
  { p: "MARIPOSA", t: ["alas", "volar", "colores", "flor", "oruga"] },
  { p: "HORMIGA", t: ["pequeña", "trabajar", "hormiguero", "fila", "azúcar"] },
  { p: "MOSQUITO", t: ["picar", "volar", "sangre", "zumbido", "verano"] },
  { p: "CARACOL", t: ["concha", "lento", "baba", "jardín", "cuernos"] },
  { p: "BÚHO", t: ["noche", "ojos", "volar", "árbol", "sabio"] },
  { p: "ÁGUILA", t: ["volar", "alas", "pico", "garras", "cielo"] },
  { p: "LORO", t: ["hablar", "colores", "pico", "volar", "pirata"] },
  { p: "PALOMA", t: ["volar", "ciudad", "gris", "paz", "plaza"] },
  { p: "MURCIÉLAGO", t: ["noche", "cueva", "volar", "alas", "vampiro"] },
  { p: "CAMELLO", t: ["desierto", "joroba", "arena", "agua", "viajar"] },
  { p: "RINOCERONTE", t: ["cuerno", "grande", "gris", "África", "fuerte"] },
  { p: "HIPOPÓTAMO", t: ["agua", "grande", "boca", "río", "gordo"] },
  { p: "ARDILLA", t: ["nuez", "árbol", "cola", "saltar", "bellota"] },
  { p: "ERIZO", t: ["púas", "pinchos", "pequeño", "bola", "espinas"] },
  { p: "FOCA", t: ["mar", "hielo", "nadar", "pescado", "bigotes"] },
  { p: "CIERVO", t: ["cuernos", "bosque", "saltar", "marrón", "rápido"] },
  { p: "DINOSAURIO", t: ["extinto", "huevo", "gigante", "prehistórico", "rugir"] },

  // ---------- COMIDA Y BEBIDA (40) ----------
  { p: "PIZZA", t: ["queso", "tomate", "italiana", "redonda", "horno"] },
  { p: "HAMBURGUESA", t: ["carne", "pan", "queso", "lechuga", "comida"] },
  { p: "PLÁTANO", t: ["fruta", "amarillo", "mono", "pelar", "curvo"] },
  { p: "MANZANA", t: ["fruta", "roja", "árbol", "morder", "Blancanieves"] },
  { p: "NARANJA", t: ["fruta", "color", "zumo", "redonda", "vitamina"] },
  { p: "FRESA", t: ["fruta", "roja", "dulce", "pequeña", "nata"] },
  { p: "UVA", t: ["fruta", "racimo", "vino", "pequeña", "morada"] },
  { p: "SANDÍA", t: ["fruta", "verde", "roja", "verano", "pepitas"] },
  { p: "LIMÓN", t: ["amarillo", "ácido", "fruta", "zumo", "agrio"] },
  { p: "PIÑA", t: ["fruta", "tropical", "amarilla", "corona", "dulce"] },
  { p: "TOMATE", t: ["rojo", "salsa", "ensalada", "redondo", "verdura"] },
  { p: "PATATA", t: ["frita", "tierra", "marrón", "puré", "tubérculo"] },
  { p: "ZANAHORIA", t: ["naranja", "conejo", "verdura", "vista", "huerto"] },
  { p: "LECHUGA", t: ["verde", "ensalada", "hojas", "verdura", "fresca"] },
  { p: "PAN", t: ["harina", "horno", "panadería", "tostada", "miga"] },
  { p: "QUESO", t: ["leche", "ratón", "amarillo", "pizza", "rallar"] },
  { p: "HUEVO", t: ["gallina", "frito", "cáscara", "blanco", "tortilla"] },
  { p: "LECHE", t: ["vaca", "blanca", "vaso", "desayuno", "cereales"] },
  { p: "CHOCOLATE", t: ["dulce", "marrón", "cacao", "tableta", "negro"] },
  { p: "HELADO", t: ["frío", "verano", "cucurucho", "dulce", "vainilla"] },
  { p: "TARTA", t: ["cumpleaños", "velas", "dulce", "nata", "trozo"] },
  { p: "GALLETA", t: ["dulce", "redonda", "leche", "horno", "chocolate"] },
  { p: "CARAMELO", t: ["dulce", "azúcar", "chuche", "palo", "pegajoso"] },
  { p: "MIEL", t: ["abeja", "dulce", "dorada", "oso", "panal"] },
  { p: "ARROZ", t: ["blanco", "grano", "paella", "China", "cocer"] },
  { p: "PASTA", t: ["espagueti", "italiana", "salsa", "macarrones", "hervir"] },
  { p: "SOPA", t: ["caliente", "cuchara", "plato", "verdura", "líquida"] },
  { p: "PESCADO", t: ["mar", "espinas", "comer", "frito", "escamas"] },
  { p: "POLLO", t: ["gallina", "carne", "asado", "ave", "muslo"] },
  { p: "JAMÓN", t: ["cerdo", "bocadillo", "rosa", "lonchas", "salado"] },
  { p: "SALCHICHA", t: ["perrito", "carne", "alargada", "rosa", "barbacoa"] },
  { p: "ZUMO", t: ["fruta", "naranja", "beber", "vaso", "exprimir"] },
  { p: "AGUA", t: ["beber", "transparente", "vaso", "líquido", "sed"] },
  { p: "PALOMITAS", t: ["maíz", "cine", "blancas", "sal", "explotar"] },
  { p: "PATATAS FRITAS", t: ["bolsa", "crujientes", "sal", "aceite", "patata"] },
  { p: "DONUT", t: ["agujero", "dulce", "redondo", "glaseado", "rosquilla"] },
  { p: "CEREALES", t: ["desayuno", "leche", "bol", "cuchara", "crujiente"] },
  { p: "MERMELADA", t: ["fruta", "dulce", "tostada", "tarro", "untar"] },
  { p: "GUISANTE", t: ["verde", "redondo", "vaina", "verdura", "pequeño"] },
  { p: "MAÍZ", t: ["amarillo", "mazorca", "granos", "palomitas", "campo"] },

  // ---------- CASA Y OBJETOS (35) ----------
  { p: "CAMA", t: ["dormir", "almohada", "sábanas", "noche", "colchón"] },
  { p: "SILLA", t: ["sentarse", "patas", "mesa", "respaldo", "madera"] },
  { p: "MESA", t: ["comer", "patas", "silla", "plana", "comedor"] },
  { p: "SOFÁ", t: ["sentarse", "salón", "cómodo", "tele", "cojines"] },
  { p: "TELEVISIÓN", t: ["ver", "pantalla", "mando", "programa", "salón"] },
  { p: "NEVERA", t: ["frío", "cocina", "comida", "puerta", "hielo"] },
  { p: "LÁMPARA", t: ["luz", "bombilla", "encender", "techo", "noche"] },
  { p: "VENTANA", t: ["cristal", "abrir", "pared", "ver", "luz"] },
  { p: "PUERTA", t: ["abrir", "cerrar", "llave", "entrar", "pomo"] },
  { p: "ESPEJO", t: ["reflejo", "mirar", "cristal", "cara", "verse"] },
  { p: "RELOJ", t: ["hora", "tiempo", "agujas", "muñeca", "tic-tac"] },
  { p: "TELÉFONO", t: ["llamar", "hablar", "móvil", "pantalla", "número"] },
  { p: "PLATO", t: ["comer", "redondo", "comida", "vajilla", "mesa"] },
  { p: "VASO", t: ["beber", "agua", "cristal", "lleno", "líquido"] },
  { p: "CUCHARA", t: ["sopa", "comer", "metal", "redonda", "cubierto"] },
  { p: "TENEDOR", t: ["comer", "pinchar", "puntas", "cubierto", "metal"] },
  { p: "CUCHILLO", t: ["cortar", "afilado", "cubierto", "filo", "metal"] },
  { p: "CEPILLO", t: ["dientes", "pasta", "baño", "limpiar", "boca"] },
  { p: "JABÓN", t: ["lavar", "espuma", "ducha", "manos", "limpio"] },
  { p: "TOALLA", t: ["secar", "baño", "ducha", "tela", "mojado"] },
  { p: "ESCOBA", t: ["barrer", "suelo", "limpiar", "palo", "bruja"] },
  { p: "LLAVE", t: ["puerta", "abrir", "cerradura", "metal", "candado"] },
  { p: "PARAGUAS", t: ["lluvia", "abrir", "mojarse", "palo", "tela"] },
  { p: "MOCHILA", t: ["espalda", "colegio", "libros", "llevar", "cremallera"] },
  { p: "TIJERAS", t: ["cortar", "papel", "dos", "afiladas", "manualidades"] },
  { p: "PEGAMENTO", t: ["pegar", "barra", "papel", "manualidades", "pegajoso"] },
  { p: "ALMOHADA", t: ["cama", "dormir", "blanda", "cabeza", "noche"] },
  { p: "MANTA", t: ["cama", "calor", "tapar", "frío", "abrigar"] },
  { p: "CORTINA", t: ["ventana", "tela", "tapar", "luz", "colgar"] },
  { p: "ALFOMBRA", t: ["suelo", "pisar", "salón", "blanda", "tela"] },
  { p: "ESCALERA", t: ["subir", "bajar", "peldaños", "piso", "escalones"] },
  { p: "VELA", t: ["fuego", "cera", "cumpleaños", "luz", "soplar"] },
  { p: "GLOBO", t: ["aire", "hinchar", "fiesta", "explotar", "volar"] },
  { p: "JUGUETE", t: ["jugar", "niño", "divertido", "regalo", "muñeco"] },
  { p: "PELUCHE", t: ["blando", "abrazar", "oso", "dormir", "muñeco"] },

  // ---------- LUGARES (20) ----------
  { p: "COLEGIO", t: ["estudiar", "profesor", "clase", "niños", "aprender"] },
  { p: "HOSPITAL", t: ["médico", "enfermo", "enfermera", "cama", "curar"] },
  { p: "PLAYA", t: ["mar", "arena", "sol", "verano", "olas"] },
  { p: "PARQUE", t: ["columpios", "jugar", "árboles", "niños", "banco"] },
  { p: "ZOO", t: ["animales", "jaula", "león", "visitar", "leones"] },
  { p: "CINE", t: ["película", "pantalla", "palomitas", "butaca", "ver"] },
  { p: "BIBLIOTECA", t: ["libros", "silencio", "leer", "estanterías", "estudiar"] },
  { p: "SUPERMERCADO", t: ["comprar", "comida", "carro", "cajera", "pasillos"] },
  { p: "RESTAURANTE", t: ["comer", "camarero", "mesa", "comida", "menú"] },
  { p: "CASTILLO", t: ["rey", "torre", "muralla", "príncipe", "antiguo"] },
  { p: "GRANJA", t: ["animales", "campo", "vaca", "tractor", "gallinas"] },
  { p: "MONTAÑA", t: ["alta", "subir", "nieve", "cima", "escalar"] },
  { p: "RÍO", t: ["agua", "corriente", "puente", "pez", "orilla"] },
  { p: "BOSQUE", t: ["árboles", "verde", "animales", "hojas", "perderse"] },
  { p: "DESIERTO", t: ["arena", "calor", "camello", "seco", "dunas"] },
  { p: "ISLA", t: ["mar", "rodeada", "agua", "palmera", "playa"] },
  { p: "CUEVA", t: ["oscura", "montaña", "murciélago", "piedra", "agujero"] },
  { p: "AEROPUERTO", t: ["avión", "volar", "viaje", "maletas", "pista"] },
  { p: "ESTACIÓN", t: ["tren", "andén", "viaje", "billete", "vía"] },
  { p: "IGLESIA", t: ["campana", "rezar", "torre", "cura", "misa"] },

  // ---------- PROFESIONES (20) ----------
  { p: "MÉDICO", t: ["hospital", "enfermo", "curar", "bata", "doctor"] },
  { p: "PROFESOR", t: ["colegio", "enseñar", "clase", "alumnos", "pizarra"] },
  { p: "BOMBERO", t: ["fuego", "camión", "apagar", "manguera", "rescatar"] },
  { p: "POLICÍA", t: ["ladrón", "ley", "coche", "uniforme", "esposas"] },
  { p: "COCINERO", t: ["comida", "cocina", "gorro", "platos", "guisar"] },
  { p: "PILOTO", t: ["avión", "volar", "cabina", "viaje", "cielo"] },
  { p: "ASTRONAUTA", t: ["espacio", "nave", "luna", "traje", "estrellas"] },
  { p: "CARTERO", t: ["cartas", "buzón", "entregar", "correo", "paquetes"] },
  { p: "PANADERO", t: ["pan", "horno", "harina", "panadería", "masa"] },
  { p: "PELUQUERO", t: ["pelo", "cortar", "tijeras", "peinar", "salón"] },
  { p: "DENTISTA", t: ["dientes", "boca", "muela", "caries", "cepillar"] },
  { p: "VETERINARIO", t: ["animales", "perro", "curar", "mascota", "clínica"] },
  { p: "GRANJERO", t: ["granja", "campo", "tractor", "animales", "cultivar"] },
  { p: "PESCADOR", t: ["pez", "caña", "mar", "barco", "red"] },
  { p: "PINTOR", t: ["pintura", "pincel", "cuadro", "colores", "pared"] },
  { p: "MÚSICO", t: ["música", "instrumento", "tocar", "canción", "notas"] },
  { p: "PAYASO", t: ["circo", "reír", "nariz", "colores", "gracioso"] },
  { p: "JARDINERO", t: ["plantas", "jardín", "flores", "regar", "césped"] },
  { p: "MECÁNICO", t: ["coche", "arreglar", "motor", "taller", "herramientas"] },
  { p: "MAGO", t: ["truco", "varita", "magia", "conejo", "chistera"] },

  // ---------- DEPORTES Y JUEGOS (20) ----------
  { p: "FÚTBOL", t: ["balón", "portería", "gol", "equipo", "patear"] },
  { p: "BALONCESTO", t: ["canasta", "balón", "encestar", "aro", "botar"] },
  { p: "TENIS", t: ["raqueta", "pelota", "red", "pista", "saque"] },
  { p: "NATACIÓN", t: ["agua", "piscina", "nadar", "bañador", "brazadas"] },
  { p: "CICLISMO", t: ["bicicleta", "pedales", "ruedas", "carrera", "casco"] },
  { p: "ATLETISMO", t: ["correr", "pista", "carrera", "saltar", "medalla"] },
  { p: "PATINAJE", t: ["patines", "ruedas", "hielo", "deslizar", "caer"] },
  { p: "ESQUÍ", t: ["nieve", "montaña", "esquís", "bajar", "invierno"] },
  { p: "BOXEO", t: ["guantes", "puñetazo", "ring", "pelear", "golpe"] },
  { p: "AJEDREZ", t: ["tablero", "rey", "fichas", "jaque", "estrategia"] },
  { p: "PARCHÍS", t: ["dado", "fichas", "tablero", "casillas", "colores"] },
  { p: "ESCONDITE", t: ["esconder", "buscar", "contar", "encontrar", "ojos"] },
  { p: "COMETA", t: ["viento", "volar", "cielo", "cuerda", "cola"] },
  { p: "COLUMPIO", t: ["balancear", "parque", "sentarse", "cadenas", "subir"] },
  { p: "TOBOGÁN", t: ["deslizar", "bajar", "parque", "resbalar", "rampa"] },
  { p: "PELOTA", t: ["redonda", "botar", "jugar", "lanzar", "rodar"] },
  { p: "CUERDA", t: ["saltar", "atar", "larga", "comba", "nudo"] },
  { p: "PUZZLE", t: ["piezas", "encajar", "imagen", "montar", "rompecabezas"] },
  { p: "VIDEOJUEGO", t: ["consola", "mando", "pantalla", "jugar", "niveles"] },
  { p: "CARRERA", t: ["correr", "rápido", "meta", "ganar", "salida"] },

  // ---------- NATURALEZA (20) ----------
  { p: "SOL", t: ["calor", "luz", "amarillo", "día", "cielo"] },
  { p: "LUNA", t: ["noche", "cielo", "blanca", "estrellas", "redonda"] },
  { p: "ESTRELLA", t: ["cielo", "noche", "brillar", "punta", "lejos"] },
  { p: "NUBE", t: ["cielo", "blanca", "lluvia", "algodón", "volar"] },
  { p: "LLUVIA", t: ["agua", "mojar", "paraguas", "gotas", "nube"] },
  { p: "NIEVE", t: ["frío", "blanca", "invierno", "muñeco", "copos"] },
  { p: "VIENTO", t: ["aire", "soplar", "fuerte", "volar", "hojas"] },
  { p: "ARCOÍRIS", t: ["colores", "lluvia", "cielo", "siete", "sol"] },
  { p: "RAYO", t: ["tormenta", "luz", "trueno", "cielo", "eléctrico"] },
  { p: "FUEGO", t: ["caliente", "llama", "quemar", "rojo", "humo"] },
  { p: "ÁRBOL", t: ["hojas", "tronco", "ramas", "verde", "raíces"] },
  { p: "FLOR", t: ["pétalos", "jardín", "olor", "colores", "planta"] },
  { p: "HOJA", t: ["árbol", "verde", "otoño", "caer", "rama"] },
  { p: "PIEDRA", t: ["dura", "suelo", "gris", "roca", "tirar"] },
  { p: "VOLCÁN", t: ["lava", "erupción", "montaña", "fuego", "explotar"] },
  { p: "MAR", t: ["agua", "olas", "salada", "azul", "playa"] },
  { p: "CASCADA", t: ["agua", "caer", "río", "altura", "salto"] },
  { p: "DESHIELO", t: ["hielo", "derretir", "agua", "frío", "primavera"] },
  { p: "TIERRA", t: ["planeta", "mundo", "redonda", "azul", "vivir"] },
  { p: "PLANETA", t: ["espacio", "redondo", "órbita", "Tierra", "Marte"] },

  // ---------- TRANSPORTE (15) ----------
  { p: "COCHE", t: ["ruedas", "conducir", "motor", "volante", "carretera"] },
  { p: "AVIÓN", t: ["volar", "alas", "cielo", "viaje", "piloto"] },
  { p: "BARCO", t: ["mar", "agua", "navegar", "flotar", "marinero"] },
  { p: "TREN", t: ["vías", "vagones", "estación", "raíles", "locomotora"] },
  { p: "BICICLETA", t: ["ruedas", "pedales", "manillar", "montar", "dos"] },
  { p: "MOTO", t: ["ruedas", "motor", "casco", "rápida", "dos"] },
  { p: "AUTOBÚS", t: ["pasajeros", "parada", "ruedas", "grande", "conductor"] },
  { p: "CAMIÓN", t: ["grande", "carga", "ruedas", "carretera", "transportar"] },
  { p: "HELICÓPTERO", t: ["hélice", "volar", "aspas", "cielo", "aterrizar"] },
  { p: "COHETE", t: ["espacio", "despegar", "fuego", "luna", "volar"] },
  { p: "SUBMARINO", t: ["mar", "agua", "bajo", "buceo", "profundo"] },
  { p: "PATINETE", t: ["ruedas", "empujar", "pie", "manillar", "rodar"] },
  { p: "GLOBO AEROSTÁTICO", t: ["aire", "volar", "cesta", "subir", "caliente"] },
  { p: "TRACTOR", t: ["granja", "campo", "ruedas", "arar", "grande"] },
  { p: "AMBULANCIA", t: ["hospital", "enfermo", "sirena", "rápida", "rescatar"] },

  // ---------- CUERPO (15) ----------
  { p: "MANO", t: ["dedos", "tocar", "brazo", "cinco", "palma"] },
  { p: "PIE", t: ["andar", "zapato", "dedos", "pierna", "caminar"] },
  { p: "OJO", t: ["ver", "mirar", "cara", "pestañas", "dos"] },
  { p: "NARIZ", t: ["oler", "cara", "moco", "respirar", "centro"] },
  { p: "BOCA", t: ["comer", "hablar", "dientes", "labios", "lengua"] },
  { p: "OREJA", t: ["oír", "escuchar", "cabeza", "sonido", "lado"] },
  { p: "PELO", t: ["cabeza", "peinar", "cortar", "rubio", "largo"] },
  { p: "DIENTE", t: ["boca", "morder", "blanco", "cepillo", "ratoncito"] },
  { p: "LENGUA", t: ["boca", "sabor", "rosa", "hablar", "lamer"] },
  { p: "BRAZO", t: ["mano", "codo", "cuerpo", "abrazar", "hombro"] },
  { p: "PIERNA", t: ["andar", "rodilla", "pie", "correr", "muslo"] },
  { p: "CORAZÓN", t: ["latir", "amor", "pecho", "bombear", "sangre"] },
  { p: "BARRIGA", t: ["tripa", "comer", "ombligo", "estómago", "lleno"] },
  { p: "ESPALDA", t: ["detrás", "columna", "cargar", "cuerpo", "tumbarse"] },
  { p: "CABEZA", t: ["pelo", "cerebro", "cara", "cuello", "pensar"] },

  // ---------- ESCUELA Y ÚTILES (15) ----------
  { p: "LÁPIZ", t: ["escribir", "punta", "madera", "grafito", "goma"] },
  { p: "GOMA", t: ["borrar", "lápiz", "errores", "blanca", "papel"] },
  { p: "CUADERNO", t: ["escribir", "hojas", "deberes", "tapas", "líneas"] },
  { p: "LIBRO", t: ["leer", "páginas", "historia", "biblioteca", "tapa"] },
  { p: "PIZARRA", t: ["tiza", "escribir", "clase", "profesor", "negra"] },
  { p: "BOLÍGRAFO", t: ["escribir", "tinta", "azul", "punta", "boli"] },
  { p: "ROTULADOR", t: ["colorear", "tinta", "punta", "colores", "pintar"] },
  { p: "REGLA", t: ["medir", "recta", "centímetros", "línea", "plástico"] },
  { p: "SACAPUNTAS", t: ["lápiz", "punta", "afilar", "girar", "viruta"] },
  { p: "PUPITRE", t: ["clase", "sentarse", "mesa", "alumno", "escribir"] },
  { p: "EXAMEN", t: ["estudiar", "preguntas", "nota", "aprobar", "prueba"] },
  { p: "DEBERES", t: ["casa", "tarea", "estudiar", "ejercicios", "profesor"] },
  { p: "RECREO", t: ["jugar", "patio", "descanso", "amigos", "colegio"] },
  { p: "MAPA", t: ["países", "geografía", "dibujo", "lugar", "mundo"] },
  { p: "TIZA", t: ["pizarra", "escribir", "blanca", "polvo", "clase"] },

  // ---------- ROPA (12) ----------
  { p: "CAMISETA", t: ["ropa", "manga", "cuerpo", "algodón", "ponerse"] },
  { p: "PANTALÓN", t: ["piernas", "ropa", "vaqueros", "cinturón", "bolsillos"] },
  { p: "ZAPATO", t: ["pie", "andar", "cordones", "calzar", "suela"] },
  { p: "CALCETÍN", t: ["pie", "zapato", "lana", "par", "ponerse"] },
  { p: "GORRO", t: ["cabeza", "frío", "lana", "invierno", "tapar"] },
  { p: "BUFANDA", t: ["cuello", "frío", "lana", "invierno", "abrigar"] },
  { p: "GUANTE", t: ["mano", "frío", "dedos", "invierno", "ponerse"] },
  { p: "ABRIGO", t: ["frío", "invierno", "ropa", "abrigar", "calor"] },
  { p: "VESTIDO", t: ["niña", "ropa", "fiesta", "falda", "ponerse"] },
  { p: "PIJAMA", t: ["dormir", "noche", "cama", "ropa", "cómodo"] },
  { p: "GAFAS", t: ["ver", "ojos", "cristales", "vista", "cara"] },
  { p: "RELOJ DE PULSERA", t: ["hora", "muñeca", "tiempo", "agujas", "llevar"] },

  // ---------- FANTASÍA Y PERSONAJES (18) ----------
  { p: "DRAGÓN", t: ["fuego", "alas", "escamas", "cola", "volar"] },
  { p: "PRINCESA", t: ["castillo", "corona", "rey", "vestido", "príncipe"] },
  { p: "BRUJA", t: ["escoba", "magia", "sombrero", "hechizo", "caldero"] },
  { p: "FANTASMA", t: ["blanco", "miedo", "casa", "susto", "transparente"] },
  { p: "VAMPIRO", t: ["sangre", "colmillos", "noche", "capa", "murciélago"] },
  { p: "UNICORNIO", t: ["cuerno", "caballo", "mágico", "blanco", "frente"] },
  { p: "SIRENA", t: ["mar", "cola", "pez", "nadar", "mujer"] },
  { p: "ROBOT", t: ["metal", "máquina", "tornillos", "luces", "andar"] },
  { p: "PIRATA", t: ["barco", "tesoro", "parche", "loro", "mar"] },
  { p: "GIGANTE", t: ["grande", "alto", "enorme", "pequeño", "fuerte"] },
  { p: "DUENDE", t: ["pequeño", "verde", "orejas", "bosque", "travieso"] },
  { p: "HADA", t: ["alas", "varita", "polvo", "volar", "mágica"] },
  { p: "MOMIA", t: ["vendas", "Egipto", "pirámide", "antigua", "tumba"] },
  { p: "ZOMBI", t: ["muerto", "andar", "verde", "miedo", "cerebro"] },
  { p: "SUPERHÉROE", t: ["capa", "poderes", "salvar", "volar", "máscara"] },
  { p: "OGRO", t: ["verde", "feo", "grande", "pantano", "Shrek"] },
  { p: "GENIO", t: ["lámpara", "deseos", "frotar", "azul", "magia"] },
  { p: "DINOSAURIO REX", t: ["dientes", "grande", "rugir", "extinto", "brazos"] },

  // ---------- TECNOLOGÍA (10) ----------
  { p: "ORDENADOR", t: ["pantalla", "teclado", "ratón", "internet", "escribir"] },
  { p: "TABLET", t: ["pantalla", "táctil", "internet", "juegos", "dedos"] },
  { p: "CÁMARA", t: ["foto", "imagen", "fotografía", "clic", "objetivo"] },
  { p: "AURICULARES", t: ["oídos", "música", "escuchar", "sonido", "cable"] },
  { p: "INTERNET", t: ["red", "wifi", "buscar", "páginas", "conectar"] },
  { p: "VIDEOJUEGO ONLINE", t: ["internet", "jugar", "consola", "amigos", "pantalla"] },
  { p: "MANDO", t: ["botones", "consola", "jugar", "controlar", "manos"] },
  { p: "BATERÍA", t: ["cargar", "energía", "móvil", "enchufe", "duración"] },
  { p: "CARGADOR", t: ["enchufe", "cable", "batería", "móvil", "energía"] },
  { p: "PANTALLA", t: ["ver", "imagen", "móvil", "tele", "brillo"] },

  // ---------- ACCIONES Y VARIOS (10) ----------
  { p: "CUMPLEAÑOS", t: ["tarta", "velas", "regalos", "fiesta", "años"] },
  { p: "NAVIDAD", t: ["regalos", "árbol", "Papá Noel", "diciembre", "belén"] },
  { p: "VACACIONES", t: ["verano", "playa", "descanso", "viaje", "colegio"] },
  { p: "FIESTA", t: ["música", "bailar", "globos", "celebrar", "amigos"] },
  { p: "REGALO", t: ["caja", "envolver", "cumpleaños", "lazo", "sorpresa"] },
  { p: "DORMIR", t: ["cama", "noche", "sueño", "ojos", "descansar"] },
  { p: "REÍR", t: ["risa", "gracioso", "feliz", "jaja", "chiste"] },
  { p: "LLORAR", t: ["lágrimas", "triste", "ojos", "pena", "pañuelo"] },
  { p: "BAILAR", t: ["música", "mover", "pista", "ritmo", "fiesta"] },
  { p: "CANTAR", t: ["voz", "canción", "música", "boca", "micrófono"] }
];

// Exportar para uso en el navegador
if (typeof window !== "undefined") {
  window.PALABRAS = PALABRAS;
}
